import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import UserNavigation from "@/components/UserNavigation";

export const dynamic = "force-dynamic";

const poppins = Poppins({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-poppins",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/favicon-16x16.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/favicon-32x32.png"
				/>
				<link
					rel="icon"
					sizes="180x180"
					href="/apple-touch-icon.png"
				/>
				<link
					rel="icon"
					href="/site.webmanifest"
				/>
			</head>
			<body className={`${poppins.className} smooth-scroll`}>
				{children}
				<UserNavigation />
			</body>
		</html>
	);
}
